project:
  type: website

website:
  title: "someboby help me"
  navbar:
    left:
      - href: index.qmd
        text: 목록1
      - about.qmd
      - href: index.qmd
        text: 목록3
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



